# SPDX-FileCopyrightText: 2026 Fabian Neumann and Iegor Riepin
#
# SPDX-License-Identifier: CC0-1.0
exclude: "^LICENSES"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
#  - id: check-added-large-files
#    args: ["--maxkb=6000"]

# Run ruff to lint and format
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.4
  hooks:
    # Run the linter.
  - id: ruff
    args: [--fix]
    # Run the formatter.
  - id: ruff-format

  # Remove output from Jupyter notebooks
- repo: https://github.com/aflc/pre-commit-jupyter
  rev: v1.2.1
  hooks:
  - id: jupyter-notebook-cleanup
    args: ["--remove-kernel-metadata"]

  # Do YAML formatting (before the linter checks it for misses)
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.16.0
  hooks:
  - id: pretty-format-yaml
    exclude: ^pixi\.lock$
    args: [--autofix, --indent, "2", --preserve-quotes]
